### ISSUE TITLE
代码我跑不起来！

### ISSUE THREAD

**Issue by Wind-Ward** [XuJian1252878/TSCAnalysis#1]
* 你好，最近我也在看篇文章！难得你写了一篇实现code，写的很不错！
* 但是代码跑不起来，你能帮帮我么？
* 我最近也在做弹幕发掘的工作，可以一起交流啊！

**Comment by XuJian1252878** [comment]
论文里面关于神经网络的改进部分我没有看懂，所以最后直接调的doc2vec这个模型来训练词向量的。如果你是对里面神经网络的实现感兴趣的话，那么这份代码是没有帮助的。因为只是调了gensim的doc2vec包。
